Add SmallHandleSearch component and its styles
koralabs/handles-shared-lit-components pull request #10
Opened 2024-10-08 18:48 UTC by Dauntless-Jacobson

2024-10-09 22:14 UTC, Dauntless-Jacobson commented
![search](https://github.com/user-attachments/assets/432b9754-94c7-49f6-8f93-44610fc322b6)

2024-10-09 23:10 UTC, Dauntless-Jacobson commented
![Screenshot 2024-10-09 160939](https://github.com/user-attachments/assets/803c4e8d-f00b-4fff-bb00-ba114c25e2d8)

2024-10-14 23:43 UTC, bigirishlion requested changes
🪣

2024-10-14 23:43 UTC, bigirishlion commented on src/web-components/SmallHandleSearch/index.ts
> +    @property({ type: String }) search: string | undefined;
Looks like this is only being used in the clearSearch. Let's remove here, in the story and jsdocs comments

2024-10-15 20:24 UTC, bigirishlion approved these changes
📛

2024-10-15 20:24 UTC, merged