Add CustomToggle component and its story
koralabs/handles-shared-lit-components pull request #11
Opened 2024-10-08 18:51 UTC by Dauntless-Jacobson

2024-10-09 22:13 UTC, Dauntless-Jacobson commented
![toggle](https://github.com/user-attachments/assets/0282c38a-d6df-48b9-be8d-b00b5116a94d)

2024-10-09 22:35 UTC, Dauntless-Jacobson commented
![togglewithcontrols](https://github.com/user-attachments/assets/96d9248d-d1cb-4352-a97c-7b16ebece155)

2024-10-10 21:55 UTC, bigirishlion requested changes
🏀

2024-10-10 21:55 UTC, bigirishlion commented on src/web-components/CustomToggle/index.ts
> + * `custom-select` Component Usage Guide
`custom-toggle`

2024-10-10 21:55 UTC, bigirishlion commented on src/web-components/CustomToggle/index.ts
> + * <custom-select isActive="${true}"></custom-select>
`<custom-toggle .isActive="${true}"></custom-toggle>`

2024-10-10 21:55 UTC, bigirishlion commented on src/web-components/CustomToggle/index.ts
> +            <svg style="width:5.5rem; height: 2.5rem; display: flex; align-items: center;" viewBox="0 0 100 50" xmlns="http://www.w3.org/2000/svg">
Let's add `cursor:pointer;` to the list of styles

2024-10-10 21:55 UTC, bigirishlion commented on src/web-components/CustomToggle/index.ts
> +            : 'M9 15h60a10 10 0 0 1 10 10v10a10 10 0 0 1-10 10H9a10 10 0 0 1-10-10V25a10 10 0 0 1 10-10z';
This isn't being used.

2024-10-10 21:55 UTC, bigirishlion commented on src/web-components/CustomToggle/index.ts
> + *
Let's also add the following to the example usage:
```
const handleEvent = (event: Event) => {
        const toggleElement = event.currentTarget as CustomToggle;
        isActive = !isActive;
        toggleElement.isActive = isActive; // Set the reactive property on the custom element
    };
```

2024-10-11 19:49 UTC, bigirishlion requested changes
Looks like just the comments `custom-select` needs to be changed still

2024-10-11 19:49 UTC, bigirishlion commented on src/web-components/CustomToggle/index.ts
> + * <custom-select isActive="${true}"></custom-select>
It doesnt look like this was changed. It still says `<custom-select>`

2024-10-14 23:24 UTC, bigirishlion approved these changes
🔍

2024-10-14 23:24 UTC, merged