Add SelectHandle component and styles
koralabs/handles-shared-lit-components pull request #12
Opened 2024-10-08 19:02 UTC by Dauntless-Jacobson

2024-10-09 22:26 UTC, Dauntless-Jacobson commented
![select](https://github.com/user-attachments/assets/45d66d99-756b-4890-8882-26f19083aa4f)

2024-10-09 22:55 UTC, Dauntless-Jacobson commented
![selectHandlewith args](https://github.com/user-attachments/assets/553882ed-eb3c-4ea6-aa3d-1dd7798fdf3c)

2024-10-15 00:10 UTC, bigirishlion requested changes
🥍

2024-10-15 00:10 UTC, bigirishlion commented on src/web-components/SelectHandle/index.ts
> +}
These should come from kora-labs-commons

2024-10-15 00:10 UTC, bigirishlion commented on src/web-components/SelectHandle/index.ts
> +    @property({ type: String }) route = '';
This isn't being used

2024-10-15 00:10 UTC, bigirishlion commented on src/web-components/SelectHandle/index.ts
> +    }
I think we should pass the imageUrl in instead of using the gateway here. This way, if we need to try a different gateway we can.

2024-10-15 15:27 UTC, Dauntless-Jacobson commented on src/helpers/KoraLabsHelpers.ts
roll up doesn't work well with the lit component SSR, but because of how we deconstructed the component its no longer needed

2024-10-16 18:24 UTC, bigirishlion requested changes
🐤

2024-10-16 18:24 UTC, bigirishlion commented on src/web-components/SelectHandle/index.ts
> +    @property({ type: Object }) handle: any = {};
I assume this is the active handle? If so, let's name this to `activeHandle` for clarity

2024-10-16 18:24 UTC, bigirishlion commented on src/web-components/SelectHandle/index.ts
> +    @property({ type: Object }) litElement!: LitElement;
Is this being used?

2025-02-05 18:51 UTC, merged