Main popup
koralabs/handles-shared-lit-components pull request #15
Opened 2024-10-10 18:40 UTC by Dauntless-Jacobson

2024-10-10 18:41 UTC, Dauntless-Jacobson commented
![mainpopargs](https://github.com/user-attachments/assets/27e88358-b46d-4093-99c8-3d83be4d2fd4)

2024-10-10 18:42 UTC, Dauntless-Jacobson commented
i will utilize the it buttons which is why it look like that currently there is a pr to fix them

2024-10-10 21:38 UTC, bigirishlion requested changes
🪣

2024-10-10 21:38 UTC, bigirishlion commented on src/web-components/MainPopup/index.ts
> +    `;
Let's continue the format of having the CSS in a separate file

2024-10-10 21:38 UTC, bigirishlion commented on src/web-components/MainPopup/index.ts
> +@customElement('main-popup')
Let's rename this web component to "confirm-popup"

2024-10-10 21:38 UTC, bigirishlion commented on src/web-components/MainPopup/index.ts
> +    }
Let's also add in an optional function for `handleCancel` that is called so we can allow the dev to hook into the event

2024-10-10 21:38 UTC, bigirishlion commented on src/stories/MainPopup.stories.ts
> +    component: 'main-popup',
Let's change to Confirm Popup (confirm-popup)

2024-10-11 19:45 UTC, bigirishlion requested changes
👍

2024-10-11 19:45 UTC, bigirishlion commented on src/web-components/ConfirmPopup/index.ts
> +
Extra line

2024-10-11 19:45 UTC, bigirishlion commented on src/web-components/ConfirmPopup/index.ts
> + *     buttonCancel="Cancel"
I think all of these have period `.` in front correct?

2024-10-11 19:45 UTC, bigirishlion commented on src/web-components/ConfirmPopup/index.ts
> +        if (this.confirmCallback) {
should this be `if (this.confirmCancel)`?

2024-10-11 19:45 UTC, bigirishlion commented on src/web-components/ConfirmPopup/index.ts
> +    @property({ type: Function }) confirmCancel: (() => void) | null = null;
`confirmCancel` is confusing. Maybe we call this `onCancel` and change `confirmCallback` to `onConfirm`

2024-10-14 20:44 UTC, bigirishlion requested changes
📦

2024-10-14 20:44 UTC, bigirishlion commented on src/stories/ConfirmPopup.stories.ts
> +        buttonCancel: { control: 'text', description: 'Text for the cancel button' },
Can we change these to `confirmButtonLabel` and `cancelButtonLabel`?

2024-10-14 20:44 UTC, bigirishlion commented on src/web-components/ConfirmPopup/index.ts
> + * `MainPopup` is a custom popup component for displaying messages and handling user actions.
`ConfirmPopup`

2024-10-14 20:44 UTC, bigirishlion commented on src/web-components/ConfirmPopup/index.ts
> + * - **buttonCancel**: (string) The label for the cancel button.
Change if changed above

2024-10-14 20:44 UTC, bigirishlion commented on src/web-components/ConfirmPopup/index.ts
> + * <main-popup
`<confirm-popup`

2024-10-14 23:53 UTC, bigirishlion approved these changes
🍨

2024-10-14 23:53 UTC, merged