Add Error Popup
koralabs/handles-shared-lit-components pull request #16
Opened 2024-10-10 20:07 UTC by Dauntless-Jacobson

2024-10-10 20:08 UTC, Dauntless-Jacobson commented
![errorPropoargs](https://github.com/user-attachments/assets/9c7fe42d-2fbb-411f-8b0f-a01d90a59988)

2024-10-10 21:06 UTC, bigirishlion requested changes
🗡️ This is looking great! Can we do a few things?
- Add a "Title" option to match handle.me's error popup (See image)
- Add slot for custom HTML below message (See image)
- Move the close icon closer to the top right. (See image but don't match the black X. it should be white)
- Add matching margin on the top and bottom

![image](https://github.com/user-attachments/assets/7197847d-4503-4c19-a4df-4c83f8b58020)

2024-10-10 21:06 UTC, bigirishlion commented on src/web-components/ErrorPopup/index.ts
> +
extra line

2024-10-10 21:06 UTC, bigirishlion commented on src/web-components/ErrorPopup/index.ts
> +    `;
Can we move this to a separate css file?

2024-10-10 22:18 UTC, Dauntless-Jacobson commented
![errorpopup12](https://github.com/user-attachments/assets/8abeda2a-ed6d-4d99-af19-3f6df18d9178)

2024-10-11 19:28 UTC, bigirishlion approved these changes
🎲

2024-10-11 19:29 UTC, merged