Add DisconnectWalletButton component and its styles
koralabs/handles-shared-lit-components pull request #8
Opened 2024-10-08 18:41 UTC by Dauntless-Jacobson

2024-10-09 22:24 UTC, Dauntless-Jacobson commented
![dissc](https://github.com/user-attachments/assets/1701d6b2-bcab-4c56-b0da-b94446034c13)

2024-10-09 23:07 UTC, Dauntless-Jacobson commented
![Uploading disargs.png…]()

2024-10-09 23:07 UTC, Dauntless-Jacobson commented
![disargs](https://github.com/user-attachments/assets/2a4c9e9a-e513-4065-8c2f-27843e817f42)

2024-10-10 22:22 UTC, bigirishlion requested changes
⚾ Looking great!

2024-10-10 22:22 UTC, bigirishlion commented on src/stories/DisconnetWalletButton.stories.ts
> +        addFunction: {
Change name to `onClick` or `handleClick`

2024-10-10 22:22 UTC, bigirishlion commented on src/stories/DisconnetWalletButton.stories.ts
> +    addFunction?: () => void;
Change name to `onClick` or `handleClick`

2024-10-10 22:22 UTC, bigirishlion commented on src/stories/DisconnetWalletButton.stories.ts
> +        .addFunction=${addFunction}>
Change name to `onClick` or `handleClick`

2024-10-10 22:22 UTC, bigirishlion commented on src/stories/DisconnetWalletButton.stories.ts
> +    addFunction: () => console.log('Wallet disconnected!'),
Change name to `onClick` or `handleClick`

2024-10-10 22:22 UTC, bigirishlion commented on src/web-components/DisconnectWalletButton/index.ts
> +    @property({ type: Function }) addFunction = () => { };
Change name to `onClick` or `handleClick`

2024-10-10 22:22 UTC, bigirishlion commented on src/web-components/DisconnectWalletButton/index.ts
> +    @property({ type: String }) help!: string;
remove help!

2024-10-10 22:22 UTC, bigirishlion commented on src/web-components/DisconnectWalletButton/index.ts
> +    @property({ type: String }) walletKey!: string;
instead of passing in walletKey, let's pass in the walletIconUrl. This way we can get rid of the global declaration above

2024-10-10 22:22 UTC, bigirishlion commented on src/web-components/DisconnectWalletButton/index.ts
> +        const icon = walletData?.icon;
mentioned above. Let's just pass in icon

2024-10-10 22:22 UTC, bigirishlion commented on src/web-components/DisconnectWalletButton/index.ts
> +                @click="${this.addFunction}"
Change name to onClick or handleClick

2024-10-11 20:11 UTC, bigirishlion requested changes
Mostly comments that need to be updated

2024-10-14 23:30 UTC, bigirishlion requested changes
🌜

2024-10-15 03:08 UTC, bigirishlion requested changes

2024-10-15 03:08 UTC, bigirishlion commented on src/web-components/DisconnectWalletButton/index.ts
> + * 1. **wallet Icon (required)**:
This should now be optional

2024-10-15 16:23 UTC, bigirishlion approved these changes
💅

2024-10-15 16:23 UTC, merged