Add SelectHandleDropdown component and its story
koralabs/handles-shared-lit-components pull request #9
Opened 2024-10-08 18:44 UTC by Dauntless-Jacobson

2024-10-09 22:16 UTC, Dauntless-Jacobson commented
![dropdown](https://github.com/user-attachments/assets/2b71f352-499d-43c7-8394-da4d84b56631)

2024-10-09 23:04 UTC, Dauntless-Jacobson commented
![dropdownHandle args](https://github.com/user-attachments/assets/0fbfe734-b5e8-473d-a63b-0e48882a0907)

2024-10-15 20:27 UTC, bigirishlion requested changes
✌️

2024-10-15 20:27 UTC, bigirishlion commented on src/web-components/DropdownButton/index.ts
> +    @property({ type: Array }) options: string[] = [];
Let's remove if not being used

2024-10-16 18:25 UTC, bigirishlion approved these changes
🧇

2024-10-16 18:26 UTC, merged